# Generated by Django 4.2.1 on 2023-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pckt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ip_src', models.CharField(max_length=255)),
                ('ip_dst', models.CharField(max_length=255)),
                ('mac_src', models.CharField(max_length=255)),
                ('mac_dst', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=255)),
                ('sport', models.IntegerField(null=True)),
                ('dport', models.IntegerField(null=True)),
            ],
        ),
    ]
